// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// // import "../styles/globals.css";
// import "../styles/index.scss"; // Ensure you have index.scss in the correct path
// import { Provider } from "react-redux";
// import store from "@/redux/store";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Homy - Real Estate React Next js Template",
//   description: "Homy is a beautiful website template designed for Real Estate Agency.",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const isDev = process.env.NODE_ENV === 'development';

//   return (
//     <html lang="en" suppressHydrationWarning={isDev}>
//       <head>
//         <meta name="keywords" content="Real estate, Property sale, Property buy" />
//         <meta name="description" content="Homy is a beautiful website template designed for Real Estate Agency." />
//         <meta property="og:site_name" content="Homy" />
//         <meta property="og:url" content="https://creativegigstf.com" />
//         <meta property="og:type" content="website" />
//         <meta property="og:title" content="Homy - Real Estate React Next js Template" />
//         <meta name="og:image" content="images/assets/ogg.png" />
//         <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
//         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
//         <meta name="theme-color" content="#0D1A1C" />
//         <meta name="msapplication-navbutton-color" content="#0D1A1C" />
//         <meta name="apple-mobile-web-app-status-bar-style" content="#0D1A1C" />
//         <link rel="icon" href="/favicon.png" sizes="any" />
//         <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,500&display=swap" />
//       </head>
//       <body className={inter.className} suppressHydrationWarning={true}>
//         <div className="main-page-wrapper">
//           <Provider store={store}>
//             {children}
//           </Provider>
//         </div>
//       </body>
//     </html>
//   );
// }


//chatgpt (but it has metadata with client)
// 'use client';

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "../styles/index.scss"; // Ensure you have index.scss in the correct path
// import { Provider } from "react-redux";
// import store from "@/redux/store";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Homy - Real Estate React Next js Template",
//   description: "Homy is a beautiful website template designed for Real Estate Agency.",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const isDev = process.env.NODE_ENV === 'development';

//   return (
//     <html lang="en" suppressHydrationWarning={isDev}>
//       <head>
//         <meta name="keywords" content="Real estate, Property sale, Property buy" />
//         <meta name="description" content="Homy is a beautiful website template designed for Real Estate Agency." />
//         <meta property="og:site_name" content="Homy" />
//         <meta property="og:url" content="https://creativegigstf.com" />
//         <meta property="og:type" content="website" />
//         <meta property="og:title" content="Homy - Real Estate React Next js Template" />
//         <meta name="og:image" content="images/assets/ogg.png" />
//         <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
//         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
//         <meta name="theme-color" content="#0D1A1C" />
//         <meta name="msapplication-navbutton-color" content="#0D1A1C" />
//         <meta name="apple-mobile-web-app-status-bar-style" content="#0D1A1C" />
//         <link rel="icon" href="/favicon.png" sizes="any" />
//         <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,500&display=swap" />
//       </head>
//       <body className={inter.className} suppressHydrationWarning={true}>
//         <div className="main-page-wrapper">
//           <Provider store={store}>
//             {children}
//           </Provider>
//         </div>
//       </body>
//     </html>
//   );
// }


// chatgpt solution where the metadata is in a separate file
// 'use client';

// import { Inter } from "next/font/google";
// import "../styles/index.scss"; // Ensure you have index.scss in the correct path
// import { Provider } from "react-redux";
// import store from "@/redux/store";
// import { metadata } from "./metadata";

// const inter = Inter({ subsets: ["latin"] });

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const isDev = process.env.NODE_ENV === 'development';

//   return (
//     <html lang="en" suppressHydrationWarning={isDev}>
//       <head>
//         <meta name="keywords" content="Real estate, Property sale, Property buy" />
//         <meta name="description" content={metadata.description as string} />
//         <meta property="og:site_name" content="Bongo Asili" />
//         <meta property="og:url" content="https://creativegigstf.com" />
//         <meta property="og:type" content="website" />
//         <meta property="og:title" content={metadata.title as string} />
//         <meta name="og:image" content="images/assets/ogg.png" />
//         <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
//         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
//         <meta name="theme-color" content="#0D1A1C" />
//         <meta name="msapplication-navbutton-color" content="#0D1A1C" />
//         <meta name="apple-mobile-web-app-status-bar-style" content="#0D1A1C" />
//         <link rel="icon" href="/favicon.png" sizes="any" />
//         <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,500&display=swap" />
//       </head>
//       <body className={inter.className} suppressHydrationWarning={true}>
//         <div className="main-page-wrapper">
//           <Provider store={store}>
//             {children}
//           </Provider>
//         </div>
//       </body>
//     </html>
//   );
// }


// this works @16.37 31 jul 2024
// // 22 jul 14.04 another chatgpt fix to get our buttons in mediagallery working (triplistingdetails)
// 'use client';

// import { Inter } from "next/font/google";
// import "../styles/index.scss"; // Ensure you have index.scss in the correct path
// import { Provider } from "react-redux";
// import store from "@/redux/store";
// import { metadata } from "./metadata";

// const inter = Inter({ subsets: ["latin"] });

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const isDev = process.env.NODE_ENV === 'development';

//   return (
//     <html lang="en" suppressHydrationWarning={isDev}>
//       <head>
//         <meta name="keywords" content="Real estate, Property sale, Property buy" />
//         <meta name="description" content={metadata.description as string} />
//         <meta property="og:site_name" content="Bongo Asili" />
//         <meta property="og:url" content="https://creativegigstf.com" />
//         <meta property="og:type" content="website" />
//         <meta property="og:title" content={metadata.title as string} />
//         <meta name="og:image" content="images/assets/ogg.png" />
//         <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
//         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
//         <meta name="theme-color" content="#0D1A1C" />
//         <meta name="msapplication-navbutton-color" content="#0D1A1C" />
//         <meta name="apple-mobile-web-app-status-bar-style" content="#0D1A1C" />
//         <link rel="icon" href="/favicon.png" sizes="any" />
//         <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,500&display=swap" />
//         {/* Include Bootstrap CSS */}
//         <link
//           href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css"
//           rel="stylesheet"
//         />
//       </head>
//       <body className={inter.className} suppressHydrationWarning={true}>
//         <div className="main-page-wrapper">
//           <Provider store={store}>
//             {children}
//           </Provider>
//         </div>
//         {/* Include Bootstrap JavaScript */}
//         <script
//           src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"
//           integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
//           crossOrigin="anonymous"
//         ></script>
//       </body>
//     </html>
//   );
// }



// // working on 16 aug @15.00
// // 18.36 31 jul 24 incorporates new wrapper Clientlayout.tsx
// import { Inter } from "next/font/google";
// import "../styles/index.scss"; // Ensure you have index.scss in the correct path
// import { metadata } from "./metadata";
// import Head from "next/head";
// import ClientLayout from "./Clientlayout"; // Import the Clientlayout

// const inter = Inter({ subsets: ["latin"] });

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const isDev = process.env.NODE_ENV === 'development';

//   return (
//     <html lang="en" suppressHydrationWarning={isDev}>
//       <Head>
//         <meta name="keywords" content="Travel, Safari, Kenya, Tanzania, Uganda, Mozambique, Namibia, South Africa" />
//         <meta name="description" content={metadata.description as string} />
//         <meta property="og:site_name" content="Bongo Asili" />
//         <meta property="og:url" content="https://creativegigstf.com" />
//         <meta property="og:type" content="website" />
//         <meta property="og:title" content={metadata.title as string} />
//         <meta name="og:image" content="images/assets/ogg.png" />
//         <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
//         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
//         <meta name="theme-color" content="#0D1A1C" />
//         <meta name="msapplication-navbutton-color" content="#0D1A1C" />
//         <meta name="apple-mobile-web-app-status-bar-style" content="#0D1A1C" />
//         <link rel="icon" href="/favicon.png" sizes="any" />
//         <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,500&display=swap" />
//         {/* Include Bootstrap CSS */}
//         <link
//           href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css"
//           rel="stylesheet"
//         />
//         {/* Include Google Maps JavaScript API */}
//         <script
//           src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&callback=initMap&libraries=maps,marker`}
//           async
//           defer
//         ></script>
//       </Head>
//       <body className={inter.className} suppressHydrationWarning={true}>
//         <div className="main-page-wrapper">
//           <ClientLayout>
//             {children}
//           </ClientLayout>
//         </div>
//         {/* Include Bootstrap JavaScript */}
//         <script
//           src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"
//           integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
//           crossOrigin="anonymous"
//         ></script>
//       </body>
//     </html>
//   );
// }

// 16 aug 15.00 updating for SEO
import { Inter } from "next/font/google";
import "../styles/index.scss"; 
import { metadata } from "./metadata";
import Head from "next/head";
import ClientLayout from "./Clientlayout";
import Wrapper from "@/layouts/Wrapper"; // Import Wrapper here

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isDev = process.env.NODE_ENV === 'development';

  return (
    <html lang="en" suppressHydrationWarning={isDev}>
      <Head>
      <meta name="keywords" content="Travel, Safari, Kenya, Tanzania, Uganda, Mozambique, Namibia, South Africa" />
      <meta name="description" content={metadata.description as string} />
        <meta property="og:site_name" content="Bongo Asili" />
        <meta property="og:url" content="https://creativegigstf.com" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content={metadata.title as string} />
        <meta name="og:image" content="images/assets/ogg.png" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="theme-color" content="#0D1A1C" />
        <meta name="msapplication-navbutton-color" content="#0D1A1C" />
        <meta name="apple-mobile-web-app-status-bar-style" content="#0D1A1C" />
        <link rel="icon" href="/favicon.png" sizes="any" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,500&display=swap" />
        {/* Include Bootstrap CSS */}
        {/* <link
          href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css"
          rel="stylesheet"
        /> */}
        {/* Include Google Maps JavaScript API */}
        <script
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&callback=initMap&libraries=maps,marker`}
          async
          defer
        ></script>
      </Head>
      <body className={inter.className} suppressHydrationWarning={true}>
        <div className="main-page-wrapper">
          <ClientLayout>
            <Wrapper> {/* Wrap children with Wrapper */}
              {children}
            </Wrapper>
          </ClientLayout>
        </div>
        {/* Include Bootstrap JavaScript */}
        {/* <script
          src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"
          integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
          crossOrigin="anonymous"
        ></script> */}
      </body>
    </html>
  );
}
